import { StyleSheet } from 'react-native'

export default StyleSheet.create({
    container:{
        backgroundColor:'#9C1C26',
        flex:1,
        alignItems:'center',
        justifyContent:'center'
    },
    button:{
        backgroundColor:'white',
        justifyContent:'center',
        alignItems:'center',
        backgroundColor:'white',
    },
    textColora:{
        color:'#9C1C26'
    },
    textColorb:{
        color:'#FFFFFF'
    },
    textColorc:{
        color:'#000000'
    },
    button__Long:{
        height:50,
    },
    button__Longa:{
        height:45,
    },
    button_short:{
        height:35,
    },
    button__Widea:{
        width:179,
    },
    button__Wideb:{
        width:168
    },
    button__Widec:{
        width:158
    },
    button__Wided:{
        width:80
    },
    button__Widee:{
        width:82
    },
    input:{
        
        height:50,
        fontSize:18
    },
    all_width:{
        width:'100%',
    },
    hideDisplay:{
        opacity:0
    },
    input_holder:{
        width:"100%",
        borderBottomColor:'rgba(255,255,255,0.8)',
        borderBottomWidth:1,
    },
    heighta:{
        height:16
    },
    widtha:{
        width:'90%'
    },
    Password__Input__Container:{
        display:'flex',
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center'
    },
    simple_Margin:{
        marginTop:10,
        marginBottom:10
    }
})

export const colors={
    b:"#ffffff",
    a:'#9C1C26',
    c:'#000000'
}