import { StyleSheet } from 'react-native'

export default StyleSheet.create({
    container:{
        backgroundColor:'#9C1C26',
        flex:1,
        justifyContent:'center'
    },
    containera:{
        backgroundColor:'white',
        borderRadius:5,
        padding:10,
        paddingBottom:0
    },
    containerb:{
        flexDirection:'row',
        justifyContent:'space-between',
        padding:15
    },
    containerc:{ 
        flexDirection:'row', 
        justifyContent:'space-between',
        borderTopWidth:1,
        borderTopColor:'rgba(0,0,0,0.2)',
        padding:10,
        paddingLeft:20,
        paddingRight:20
    },
    containerd:{
        flexDirection:'row', 
        justifyContent:'space-between',
        width:70
    },
    containere:{
        width: 20, 
        height: 20,
        alignSelf:'flex-end'
    },
    containerf:{
        padding:5,
        alignSelf:'stretch',
        borderRadius:20,
        borderColor:'#9C1C26',
        borderWidth:2
    },
    button:{
        backgroundColor:'white',
        justifyContent:'center',
        alignItems:'center',
        backgroundColor:'white',
    },
    toucha:{
        padding:20,
        backgroundColor:'rgba(0,0,0,0.05)',
        borderRadius:50
    },
    dimensiona:{
        width: 25, 
        height: 25,
    },
    flexa:{
        alignItems:'center'
    },
    textColora:{
        color:'#9C1C26'
    },
    textColorb:{
        color:'#FFFFFF'
    },
    textColorc:{
        color:'#000000'
    },
    button__Long:{
        height:50,
    },
    button__Longa:{
        height:45,
    },
    button_short:{
        height:35,
    },
    button__Widea:{
        width:179,
    },
    button__Wideb:{
        width:168
    },
    button__Widec:{
        width:158
    },
    button__Wided:{
        width:80
    },
    button__Widee:{
        width:82
    },
    input:{
        
        height:50,
        fontSize:18
    },
    all_width:{
        width:'100%',
    },
    hideDisplay:{
        opacity:0
    },
    input_holder:{
        width:"100%",
        borderBottomColor:'rgba(255,255,255,0.8)',
        borderBottomWidth:1,
    },
    heighta:{
        height:16
    },
    widtha:{
        width:'90%'
    },
    Password__Input__Container:{
        display:'flex',
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center'
    },
    simple_Margin:{
        marginTop:10,
        marginBottom:10
    },
    textWeight:{
        fontWeight:'bold'
    }
})

export const colors={
    b:"#ffffff",
    a:'#9C1C26',
    c:'#000000'
}